### ISSUE TITLE
Respuestas de Slackbot, pero con reactions

### ISSUE THREAD

**Issue by emanuelandrada** [Javier-Rotelli/taperbot#13]
Sirve para manijear sin llenar de mensajes nuevos. Ideal para el pato.
La idea sería que sea configurable de alguna forma, por ejemplo:
`@taperbot /reaction pato :cuac:`
Ese comando agrega (o quita, si ya está) ese reaction a la lista de reactions que se agregan a los mensajes que contengan esa palabra o frase.
Si a un mensaje aplica más de un reaction estos se randomean y luego se aplican los n primeros, siendo n un número al azar entre 1 y la cantidad de reactions que aplican.
No sé si hay algún tipo de persistencia, pero debería haberla para guardar la configuración.
Deseable:
`@taperbot /reaction list`
para ver los reactions configurados

**Comment by Javier-Rotelli** [comment]
Closed on #16

**Comment by morhook** [comment]
Alto issueeeeee
